apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flipkart-eks-cluster
  region: us-east-1

nodeGroups:
  - name: flipkart-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-load-balancer-controller

iam:
  withOIDC: true
