apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flipkart-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elsonpulikkan96/Flipkart-DevSecops-EKS-Scout-OWASP-ZAP-Gitops-project
    targetRevision: main
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: flipkart-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
